### ISSUE TITLE
Search appartment will clear select apps

### ISSUE THREAD

**Issue by cyl3392207** [luffy-xiao/HTMS#12]
http://localhost:9523/main.html#/contract/create

try to query available appartments. Rest API returns but UI doesn't show

**Comment by cyl3392207** [comment]
The previous issue seems not repro. However another issue come with tite updated

**Comment by cyl3392207** [comment]
when you removed the last selected appartment in this page, the two buttons will be still there with an empty line. Plase make sure you can delete and readd repeatedly

**Comment by luffy-xiao** [comment]
will check it. :smile:

**Comment by luffy-xiao** [comment]
This is because every remove action `calcuateapps` will be called even if all selected are removed.
