### ISSUE TITLE
when filter appartments, if I clear building number, then the query will fail

### ISSUE THREAD

**Issue by cyl3392207** [luffy-xiao/HTMS#13]
http://localhost:9523/main.html#/contract/create

Type building 1 , and clear "1". Query appartment will return 400

**Comment by cyl3392207** [comment]
Please check other places as well. This may be due to null or "" empty string.

**Comment by luffy-xiao** [comment]
the code already check null or empty string, can't reproduce with above.
may enter some non-number string. will do a validation on number if not empty.

**Comment by cyl3392207** [comment]
update repro steps

we need to select size range as well.

**Comment by cyl3392207** [comment]
Request URL: http://localhost:9523/api/Appartments?$filter=true+and+CommunityId+eq+1+and+BuildingNumber+eq++and+Size+gt+90+and+Status+ne+'%E5%B7%B2%E5%94%AE'&$inlinecount=allpages&$orderby=BuildingNumber,UnitNumber,DoorNumber&$skip=0&$top=20

Response 400
{"Message":"The query specified in the URI is not valid. Syntax error at position 57 in 'true and CommunityId eq 1 and BuildingNumber eq  and Size gt 90 and Status ne '已售''.","ExceptionMessage":"Syntax error at position 57 in 'true and CommunityId eq 1 and BuildingNumber eq  and Size gt 90 and Status ne '已售''.","ExceptionType":"Microsoft.Data.OData.ODataException","StackTrace":"   at Microsoft.Data.OData.Query.ExpressionLexer.ValidateToken(ExpressionTokenKind t)\r\n   at Microsoft.Data.OData.Query.UriQueryExpressionParser.ParseFilter(String filter)\r\n   at Microsoft.Data.OData.Query.ODataUriParser.ParseFilterImplementation(String filter, IEdmType elementType, IEdmEntitySet entitySet)\r\n   at System.Web.Http.OData.Query.FilterQueryOption.get_FilterClause()\r\n   at System.Web.Http.OData.Query.Validators.FilterQueryValidator.Validate(FilterQueryOption filterQueryOption, ODataValidationSettings settings)\r\n   at System.Web.Http.OData.Query.FilterQueryOption.Validate(ODataValidationSettings validationSettings)\r\n   at System.Web.Http.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)\r\n   at System.Web.Http.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)\r\n   at System.Web.Http.OData.EnableQueryAttribute.ValidateQuery(HttpRequestMessage request, ODataQueryOptions queryOptions)\r\n   at System.Web.Http.OData.EnableQueryAttribute.ExecuteQuery(Object response, HttpRequestMessage request, HttpActionDescriptor actionDescriptor)\r\n   at System.Web.Http.OData.EnableQueryAttribute.OnActionExecuted(HttpActionExecutedContext actionExecutedContext)"}

**Comment by luffy-xiao** [comment]
can not repro with latest code. have you pulled the latest code?

**Comment by cyl3392207** [comment]
not reporo with latest code. Closing the issue
