### ISSUE TITLE
When selecting apartments for contract, same apartment can be selected multiple times

### ISSUE THREAD

**Issue by luffy-xiao** [luffy-xiao/HTMS#16]
http://localhost:9523/main.html#/contract/create

Select one apartment at first, and then the same apartment still could be selected.

Solution 1: filter selected apartments out when querying api
Solution 2: alert user either in apartments modal or when modal closed returning contract create page.

**Comment by cyl3392207** [comment]
if use selected the same appartment, just make the selection void.
