### ISSUE TITLE
拆迁记录,安置记录，购房记录，打印，导出excel功能

### ISSUE THREAD

**Issue by cyl3392207** [luffy-xiao/HTMS#19]
导出原始数据，选择字段列表。具体详见楼上系统（待细化）

**Comment by cyl3392207** [comment]
1. 关于打印，我们列出所有拆迁中的字段，让用户选择。（作为advanced选项）
2. 设置一些hardcode的模板，一件选择多个固定字段。
3. 使用bulkcreate中的 grid 组建列出改列表。
   4.打印表格

**Comment by cyl3392207** [comment]
Updated title to include all print work

**Comment by luffy-xiao** [comment]
动迁补偿款发放明细表

动拆迁情况

xxx基地动迁面积及补偿金额汇总表

xxx基地评估总面积汇总表

动迁户人口及房屋有效面积认定汇总表

过渡费发放汇总表

xxx基地拆迁户付款汇总表

xxx基地兑换安置房金额转入新村办清册

xxx基地动迁户水电费情况

xxx基地安置面积汇总表

xxx基地大病补助汇总表
